Remove older backup copies, n most recent backups are retained

diff --git a/websites-db-backup b/websites-db-backup
--- a/websites-db-backup
+++ b/websites-db-backup
@@ -13,121 +13,172 @@
 # for instructions.
 #
 # Before running, create a backup MySQL user with limited privileges - this allows
-# you to safely add the MySQL user password in this script. See `create-backup-user.sql`
-# in this repo.
+# you to safely add the MySQL user password in this script, which is essential when
+# the script is adapted for use on a public-facing server. See `create-backup-user.sql`
+# in this repo for instructions on creating a MySQL backup user.
 # ------------------------------------------------------------------------------
 
-# Setup variables
+# Config
 # ------------------------------------------------------------------------------
-# Doc root
-DOCROOT="/var/www/html"
-# Backup Location
-PARENT="/home/david/atest"
-# The source for rsync:
-SRC="${PARENT}/source/"
-# The storage directory:
-STORAGE="${PARENT}/backup"
-# Timestamp for directory name:
-TIMESTAMP=$(date "+%Y-%m-%d-%H:%M:%S")
-# Path to the dumped databases - NB this isn't the final destination
-DB_SRC="${SRC}sql"
-# The target directory:
-TRG="${STORAGE}/${TIMESTAMP}"
-# The link destination directory: Used to compare changes
-LNK="${STORAGE}/current"
+DOCROOT="/var/www/html" # The server document root to be backed up - in this case, Apache
 
-# Set up directories if they don't already exist
-mkdir -p $SRC # This will create $PARENT as well if it doesn't exist
+PARENT="/home/david/atest" # Location of the backup
+
+HOST="localhost" # Local MySQL hostname
+
+USER="backup_user" # MySQL backup username
+
+PASSWORD="nicelongpassword" # MySQL backup user password
+
+NUMBER_TO_KEEP=5 # The number of backups to keep. Older backups will be removed
+
+# No Edit - you probably don't need to edit below this line
+# ------------------------------------------------------------------------------
+RETAIN_NUMBER=$(( $NUMBER_TO_KEEP + 2 )) # Correction to account for n+1 and the `current` directory
+
+SRC="${PARENT}/source/" # The source for rsync
+
+STORAGE="${PARENT}/backup" # The storage directory
+
+TIMESTAMP=$(date "+%Y-%m-%d-%H:%M:%S") # Timestamp for directory name:
+
+DB_SRC="${SRC}sql" # Path to the dumped databases - NB this isn't the final destination
+
+TRG="${STORAGE}/${TIMESTAMP}" # The target directory
+
+LNK="${STORAGE}/current" # The link destination directory: Used to compare changes
+
+mkdir -p $SRC # This will also create $PARENT as well if it doesn't exist
 mkdir -p $STORAGE # Backup directory
 mkdir -p $DB_SRC # Database backup subdirectory
 mkdir -p $TRG # Final backup location, subdir of $STORAGE
-mkdir -p $LNK
+mkdir -p $LNK # The comparison directory used as the rsync `--link-dest`
+ln -s $DOCROOT $SRC # Create a symlink to $DOCROOT in $SRC
 
-ln -s $DOCROOT $SRC
-
-# Local MySQL hostname:
-HOST="localhost"
-
-# Backup databases
 # ------------------------------------------------------------------------------
-USER="backup_user"
-PASSWORD="nicelongpassword"
-HOST="localhost"
-DB_BACKUP_PATH=$DB_SRC
-
-# Get an array of databases, but not 'Database' or 'information_schema'
-DATABASES=$(mysql --user=$USER --password=$PASSWORD -e "SHOW DATABASES;" | grep -Ev "(Database|information_schema)")
-
-DUMPFAIL=false
-
-# Remove previous dumped databases
-rm $DB_BACKUP_PATH/*
-
-# Set up a log
-echo "Database backup report. ${TIMESTAMP}" > $DB_BACKUP_PATH/DB_LOG
-echo "=======================================" >> $DB_BACKUP_PATH/DB_LOG
-
-# Create dumps for each database
+# Dump databases into $PARENT/$SOURCE directory
+#
+# Uses mysqldump, backs up databases individually.
+#
 # ------------------------------------------------------------------------------
-for DB in $DATABASES
-do
+function dump_databases_into_source {
 
-  mysqldump --user=$USER --password=$PASSWORD --single-transaction --host=$HOST $DB > $DB_BACKUP_PATH/$DB.sql
+  # Get an array of databases, but not 'Database' or 'information_schema'
+  DATABASES=$(mysql --user=$USER --password=$PASSWORD -e "SHOW DATABASES;" | grep -Ev "(Database|information_schema)")
 
-  # Log the result of mysqldump
-  if [[ $? -eq 0 ]]
+  DUMPFAIL=false
 
-  then
+  # Remove previous dumped databases
+  rm $DB_SRC/*
 
-    echo -e "Mysqldump created ${DB}.sql on ${TIMESTAMP}." >> $DB_BACKUP_PATH/DB_LOG
+  # Set up a log
+  echo "Database backup report. ${TIMESTAMP}" > $DB_SRC/DB_LOG
+  echo "=======================================" >> $DB_SRC/DB_LOG
 
-  else
+  # Create dumps for each database
+  for DB in $DATABASES
+  do
 
-    echo "Mysqldump encountered a problem backing up ${DB} on ${TIMESTAMP}. Look in ${DB_BACKUP_PATH}/${DB}.log for information." >> $DB_BACKUP_PATH/DB_LOG
-    $DUMPFAIL=true
+    mysqldump --user=$USER --password=$PASSWORD --single-transaction --host=$HOST $DB > $DB_SRC/$DB.sql
 
-  fi
+    # Log the result of mysqldump
+    if [[ $? -eq 0 ]]
 
-done
+    then
 
-# The rsync options: follow the symlinks to make a hard backup
+      echo -e "Mysqldump created ${DB}.sql on ${TIMESTAMP}." >> $DB_SRC/DB_LOG
+
+    else
+
+      echo "Mysqldump encountered a problem backing up ${DB} on ${TIMESTAMP}. Look in ${DB_BACKUP_PATH}/${DB}.log for information." >> $DB_SRC/DB_LOG
+      $DUMPFAIL=true
+
+    fi
+
+  done
+
+}
+
+# ------------------------------------------------------------------------------
+# Rsync the source directory to the backup directory - the last backup used as comparator
+#
+# The rsync options: follow the symlinks to make a hard backup.
 # Exclude zip files (otherwise backupbuddy will cause enormous backups)
 # ------------------------------------------------------------------------------
-OPT=(-avL --progress --delete --exclude='*.zip' --link-dest=$LNK)
+function rsync_backup {
 
-# Execute the backup
-# ------------------------------------------------------------------------------
+  OPT=(-avL --progress --delete --exclude='*.zip' --link-dest=$LNK) # rsync options
 
-rsync "${OPT[@]}" $SRC $TRG
+  rsync "${OPT[@]}" $SRC $TRG
 
-# Log Results of Rsync
-# ------------------------------------------------------------------------------
-if [[ $? -gt 0 ]]
-then
-  # rsync Failure
-  echo "ERROR. rsync didn't complete the proper backup: ${TIMESTAMP}" >> /var/log/server-backup.log
-  # enable the next line for the server version, or if you've set up a local mailserver
-  # echo "There was an error in the nightly backup for XXX: ${TIMESTAMP}"| mail -s "Backup Error, XXX" info@example.com
-else
-  # rsync Success
-  # ----------------------------------------------------------------------------
-  if [[ false == $DUMPFAIL ]]
+  # Log Results of Rsync
+  if [[ $? -gt 0 ]]
+  then
+    # rsync Failure condition
+    echo "ERROR. rsync didn't complete the proper backup: ${TIMESTAMP}" >> /var/log/server-backup.log
+    # enable the next line for the server version, or if you've set up a local mailserver
+    # echo "There was an error in the nightly backup for XXX: ${TIMESTAMP}"| mail -s "Backup Error, XXX" info@example.com
+  else
+    # rsync Success condition
+    if [[ false != $DUMPFAIL ]]
 
-    # rsync & mysqldump worked OK
-    # --------------------------------------------------------------------------
-    then
-      echo "SUCCESS. Backup made on: ${TIMESTAMP}" >> /var/log/server-backup.log
-      #echo -e "${TIMESTAMP}: Server XXX successfully ran a local backup.\nBoth rsync & mysqldump report success."| mail -s "Backup Success, XXX" info@carawebs.com
+      # rsync & mysqldump worked OK
+      then
+        echo "SUCCESS. Backup made on: ${TIMESTAMP}" >> /var/log/server-backup.log
+        #echo -e "${TIMESTAMP}: Server XXX successfully ran a local backup.\nBoth rsync & mysqldump report success."| mail -s "Backup Success, XXX" info@carawebs.com
 
-    # rsync worked but there was at least one mysqldump error
-    # --------------------------------------------------------------------------
-    else
-      echo "PARTIAL SUCCESS. File backup (rsync) was successful, but mysqldump reports errors: ${TIMESTAMP}" >> /var/log/server-backup.log
-      #echo -e "${TIMESTAMP}: Server XXX ran a local backup.\nFile backup reports success, however mysqldump reports at least one problem.\nCheck "| mail -s "Backup Success, XXX" info@caraw$
+      # rsync worked but there was at least one mysqldump error
+      else
+        echo "PARTIAL SUCCESS. File backup (rsync) was successful, but mysqldump reports errors: ${TIMESTAMP}" >> /var/log/server-backup.log
+        #echo -e "${TIMESTAMP}: Server XXX ran a local backup.\nFile backup reports success, however mysqldump reports at least one problem.\nCheck "| mail -s "Backup Success, XXX" info@caraw$
+
+    fi
 
   fi
 
-fi
+}
 
-rm -f $STORAGE/current/*
-ln -s $TRG $STORAGE/current
+# ------------------------------------------------------------------------------
+# Remove the symlink to the target directory from `$STORAGE/current` and add a
+# symlink to the most recent copied directory to `$STORAGE/current`.
+#
+# This allows rsync to use the most recent backup as the `--link-dest` comparison
+# on the next run.
+#
+# See: http://stackoverflow.com/a/34862475
+# ------------------------------------------------------------------------------
+function setup_for_next_run {
+
+  rm -f $STORAGE/current/*
+  ln -s $TRG $STORAGE/current
+
+}
+
+# ------------------------------------------------------------------------------
+# Working notes for deletions
+# ----------------------------
+# NUMBER_TO_KEEP=5
+# ls -cp --time-style=full-iso $STORAGE | tail -n +$NUMBER_TO_KEEP | xargs -d '\n' echo rm -rf --
+# ------------------------------------------------------------------------------
+
+# ------------------------------------------------------------------------------
+# Remove old backup directories.
+#
+# Retains n directories, set in the config area of this script.
+# ------------------------------------------------------------------------------
+function delete_oldest_n_copies {
+
+  # Dry run
+  #ls -cp $STORAGE | tail -n +$RETAIN_NUMBER | xargs -d '\n' echo rm -rf --
+
+  ls -cp $STORAGE | tail -n +$RETAIN_NUMBER | xargs -d '\n' /bin/rm -rf --
+
+}
+
+dump_databases_into_source
+
+rsync_backup
+
+setup_for_next_run
+
+delete_oldest_n_copies
